### ISSUE TITLE
Hello I need a question answered please tell me

### ISSUE THREAD

**Issue by Blooket-dude** [Dentamon/The-Blooket-Hack#3]
@ZasticBradyn is there a way you can code a script to give more than 500 coins Im trying to get all the blooks in the game permenetly?

**Comment by Dentamon** [comment]
I think Blooket will ban you if they see you got more than 500 a day.  I suggest try saving up, then do the spam open boxes hack!

**Comment by Blooket-dude** [comment]
thats fine but are ou able to do that for me?
