### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by Blooket-dude** [Dentamon/The-Blooket-Hack#4]
@ZasticBradyn is there a way you can code a script to give more than 500 coins Im trying to get all the blooks in the game permenetly?

you closed the other issue. 

is their a way you could make this for me though?

**Comment by Blooket-dude** [comment]
@ZasticBradyn Also can you code something for getting all chromas permenetly. 

And can you import your hacks and stuff onto my repo?

**Comment by ZasticBradyn** [comment]
> @ZasticBradyn Also can you code something for getting all chromas permenetly.
> 
> And can you import your hacks and stuff onto my repo?

It's impossible to make a hack that gives over 500 coins, and no i will not be uploading my cheats onto any other repo, But you can fork the repository if you would like to.
also, no, you can't get all chromas permanently.
-zastix

**Comment by Blooket-dude** [comment]
ok
