### ISSUE TITLE
Can i get your blooket username.

### ISSUE THREAD

**Issue by ZasticBradyn** [Dentamon/The-Blooket-Hack#5]
Hey, its me again, im currently working on a Developer-only version of the [BlooketUI](https://github.com/ZasticBradyn/BlooketUI) so if you could give me your blooket username i will add you to the Developer only [version](https://github.com/ZasticBradyn/BlooketUI/blob/main/DevScript.js) of the script.

**Comment by ZasticBradyn** [comment]
note: i will be uploading the dev script when i get your username

**Comment by Dentamon** [comment]
Dentamon
