### ISSUE TITLE
might wanna make this private

### ISSUE THREAD

**Issue by ZasticBradyn** [Dentamon/The-Blooket-Hack#8]
currently any script editing react values ban your account, so i thouht ide let you know that u might wanna make these private until i come out with a bypass ([here](https://github.com/ZasticBradyn/BlooketCheatTools/tree/main/bypasses))

**Comment by ZasticBradyn** [comment]
or code a bypass yourself

**Comment by Dentamon** [comment]
can u add yours pls thanks!
